image: registry.gitlab.gnome.org/gnome/mutter/master:v4

stages:
 - build

build-libdecoration:
  stage: build
  script:
    - meson . build -Dbuildtype=debugoptimized --werror --prefix /usr
    - ninja -C build
    - ninja -C build install
  only:
    - merge_requests
    - /^.*$/
